#!/usr/bin/env node
/**
 * Hook support for localisation, in two modes.
 *
 *   node locale-guard.mjs generated   PreToolUse: refuse a write to a generated translation file
 *   node locale-guard.mjs drift       Stop: report locale drift once the turn is finishing
 *
 * `generated` exists because everything under `site/i18n/<locale>/` is output. An edit there looks like
 * it worked, renders correctly, and is silently reverted by the next translation run. Blocking the write
 * and naming the source to edit instead is cheaper than discovering it later from a diff that undid
 * somebody's afternoon.
 *
 * `drift` exists because the two commands that catch a half-finished locale change are easy to skip.
 * Both are fast and neither costs money, so running them at the end of a turn that touched anything
 * locale-shaped turns "I forgot to re-run the pipeline" into a line of output.
 *
 * Reads the hook payload from stdin. Exit 2 blocks with stderr shown; exit 0 with stdout is advisory.
 */
import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
/** audit/hooks -> audit -> epic-devhub -> workspace root. */
const ROOT = resolve(HERE, '..', '..', '..');

const mode = process.argv[2] ?? 'generated';

/* ------------------------------------------------------------------ generated */

/**
 * Anything the translation pipeline writes.
 *
 * `i18n/en/` is included: it is generated by `docusaurus write-translations` and consumed by the UI pass,
 * so hand-editing it is the same mistake with an extra step, and its footer `copyright` key must stay
 * absent or that locale's version numbers freeze.
 */
const GENERATED = [
  { pattern: /epic-devhub[/\\]site[/\\]i18n[/\\][^/\\]+[/\\].*\.mdx?$/i,
    fix: 'Edit the English page under epic-devhub/site/docs, then: cd epic-i18n && npm run docs' },
  { pattern: /epic-devhub[/\\]site[/\\]i18n[/\\][^/\\]+[/\\].*\.json$/i,
    fix: 'Edit the translate() call or the label in docusaurus.config.js, then: npm run write-translations in the site, and cd epic-i18n && npm run ui' },
];

function guardGenerated(payload) {
  const path = filePathFrom(payload);
  if (!path) process.exit(0);

  const hit = GENERATED.find((g) => g.pattern.test(path));
  if (!hit) process.exit(0);

  process.stderr.write(
    `${path} is generated by epic-i18n and the next run overwrites it.\n\n${hit.fix}\n\n` +
      'If you genuinely need to bypass this, say so explicitly and edit with a shell command.\n',
  );
  process.exit(2);
}

/** The tool payload names the file differently depending on the tool, so try the known shapes. */
function filePathFrom(payload) {
  const input = payload?.tool_input ?? payload?.toolInput ?? payload ?? {};
  const candidate =
    input.path ?? input.file_path ?? input.filePath ?? input.targetFile ?? input.target_file ?? null;
  return typeof candidate === 'string' ? candidate : null;
}

/* ---------------------------------------------------------------------- drift */

/**
 * Did this turn touch anything that changes what needs translating?
 *
 * Deliberately broad. The cost of a false positive is two fast commands; the cost of a false negative is
 * a locale that silently serves English.
 */
const TOUCHES_LOCALES = /(locales\.json|epic-i18n[/\\]|site[/\\]i18n[/\\]|site[/\\]docs[/\\]|site[/\\]src[/\\]|docusaurus\.config\.js|sidebars\.js|static[/\\]img[/\\]flags[/\\])/i;

function reportDrift(payload) {
  const files = editedFiles(payload);
  if (files.length && !files.some((f) => TOUCHES_LOCALES.test(f))) process.exit(0);

  const lines = [];
  const check = run('node', [join(ROOT, 'tools', 'locales.mjs'), 'check'], ROOT);
  if (check.code !== 0) {
    lines.push('locale registry check FAILED:');
    lines.push(...failureLines(check));
  }

  const i18n = join(ROOT, 'epic-i18n');
  if (existsSync(join(i18n, 'status.mjs'))) {
    const status = run('node', [join(i18n, 'status.mjs')], i18n);
    if (status.code !== 0) {
      lines.push('translation status reports work outstanding:');
      lines.push(...failureLines(status));
    }
  }

  /*
   * Reader-visible strings the translation pass cannot see.
   *
   * Reported rather than treated as a failure. A hardcoded string is a real gap, but it is a gap in the
   * source rather than in the translations, and it is not always the current job to close it. What
   * matters is that it stops being invisible: this is the check that would have caught two protocol
   * diagrams rendering in English on a fully translated page.
   */
  if (existsSync(join(i18n, 'find-untranslated.mjs'))) {
    const untranslated = run('node', [join(i18n, 'find-untranslated.mjs')], i18n);
    if (untranslated.code !== 0) {
      const summary = `${untranslated.stdout}\n${untranslated.stderr}`
        .split('\n')
        .filter((l) => /string\(s\) (?:in|no translation)/.test(l))
        .slice(0, 8)
        .map((l) => `  ${l.trim()}`);
      if (summary.length) {
        lines.push('strings no translation pass can see (wrap them in translate()):');
        lines.push(...summary);
      }
    }
  }

  if (lines.length === 0) process.exit(0);

  process.stdout.write(
    `${lines.join('\n')}\n\n` +
      'Fix before reporting the work done. See .kiro/steering/epic-locales.md.\n',
  );
  process.exit(0);
}

/** Only the lines that say what is wrong, so the report stays short enough to read. */
function failureLines(result) {
  return `${result.stdout}\n${result.stderr}`
    .split('\n')
    .filter((l) => /FAIL|problem\(s\)|stale|missing|invalid|orphan|CHANGED WITHOUT/.test(l))
    .slice(0, 12)
    .map((l) => `  ${l.trim()}`);
}

function editedFiles(payload) {
  const list = payload?.edited_files ?? payload?.editedFiles ?? payload?.files ?? [];
  return Array.isArray(list) ? list.filter((f) => typeof f === 'string') : [];
}

function run(command, args, cwd) {
  try {
    const stdout = execFileSync(command, args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
    return { code: 0, stdout, stderr: '' };
  } catch (error) {
    return { code: error.status ?? 1, stdout: error.stdout ?? '', stderr: error.stderr ?? '' };
  }
}

/* ---------------------------------------------------------------------- stdin */

function readStdin() {
  return new Promise((done) => {
    if (process.stdin.isTTY) return done(null);
    let raw = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (chunk) => { raw += chunk; });
    process.stdin.on('end', () => {
      try { done(JSON.parse(raw)); } catch { done(null); }
    });
    /* A hook must never hang a turn waiting for input that is not coming. */
    setTimeout(() => done(null), 2000).unref?.();
  });
}


/* --------------------------------------------------------------------- entry */

/*
 * Dispatch last, after every `const` this file uses is initialised.
 *
 * Not a style choice. Running it at the top threw a ReferenceError on the `const GENERATED` below it,
 * and a hook that exits non-zero for any reason other than a deliberate block is treated as a silent
 * failure: it is installed, it runs, it does nothing, and nothing says so. Which is precisely the class
 * of failure this hook exists to catch.
 */
const payload = await readStdin();

if (mode === 'generated') guardGenerated(payload);
else if (mode === 'drift') reportDrift(payload);
else {
  process.stderr.write(`unknown mode "${mode}". Use "generated" or "drift".\n`);
  process.exit(2);
}
